export const RMQ_SERVICE = {
  AUTH_SERVICE: "AUTH_SERVICE",
  PRESENCE_SERVICE: "PRESENCE_SERVICE",
} as const;

export const RMQ_SERVICE_QUEUE = {
  [RMQ_SERVICE.AUTH_SERVICE]: "RABBITMQ_AUTH_QUEUE",
  [RMQ_SERVICE.PRESENCE_SERVICE]: "RABBITMQ_PRESENCE_QUEUE",
} as const;
