version: "3.8"
name: messenger-api
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

  auth:
    container_name: messenger-api-auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  presence:
    container_name: messenger-api-presence
    build:
      context: .
      dockerfile: ./apps/presence/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  gateway:
    container_name: messenger-api-gateway
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
